### PR TITLE
updated: add custom Head hook to recipe editor template

### PR DESCRIPTION
**Pull request by newash**
If I haven't mentioned earlier: the HTML fix is because you can't have a DIV inside of a P.
Of course browsers handle it in some way even if it's broken, but it's cleaner to have it properly.

### CODE REVIEW

**Comment by hgezim** [comment]
@newash I've changed the template engine to Twig. The JS escape won't work.

**Comment by newash** [comment]
Oooh... my mistake. That escaping probably would have scrambled all my JavaScript.
Should be fine now.

**Comment by newash** [comment]
Oooo... closed? Just like that?
Not that this merge request was in my thoughts every day, but I'm still surprised.

No further questions from your side, no explanation why you decided you didn't need it.

I'm curious though: what was the problem with the patch?

Cheers

**Comment by hgezim** [comment]
Fair point. Decided I'm not comfortable adding a single line of code for one user.

**Pull request closed without merging**
